### ISSUE TITLE
How to make operator work across namespaces?

### ISSUE THREAD

**Issue by benmathews** [operator-framework/helm-app-operator-kit#18]
I've got a helm chart that will install an instance of our companies software for test purposes. Generally, I install one per namespace. I'd like to have an operator that watches for a CRD anywhere in the cluster and then makes the appropriate changes there. Not my preference, but it would also work if the CRD was placed in the operator namespace and had a destination namespace key that the operator used on. 

Is this possible?

**Comment by ecordell** [comment]
It's not currently possible, and it's by design. The Helm App Operator Kit is specifically targeting 
[OLM](https://github.com/operator-framework/operator-lifecycle-manager), which treats operators as local to a namespace.

We are looking at ways to implement operators that can watch multiple namespaces, but we're trying to do that conservatively. It wouldn't be a big deal for a test case like you described, but there are lots of concerns with doing that generically and for a long-lived, production cluster.

**Comment by benmathews** [comment]
Disappointing, but understood. It is a nice tool with a lot of potential.
