### ISSUE TITLE
Publish a Docker Image to Public Registry

### ISSUE THREAD

**Issue by cpitman** [operator-framework/helm-app-operator-kit#56]
The current usage instructions require the user to clone this repository then execute a docker build, which builds the operator itself as well as copies in the helm chart. For my own experimentation, I executed the build to create a reusable docker base image. For my operators, I start with that base image, set environment variables, then copy in the chart. Like this:

```
FROM quay.io/cpitman/helm-app-operator
ENV API_VERSION cop.redhat.com/v1alpha1
ENV KIND SpringBootApp
ENV HELM_CHART /basic-spring-boot
ADD /basic-spring-boot/ /basic-spring-boot
```

This feels like a much easier way to work with the operator, since many build systems (like Quay) don't support setting build arguments.

Could one of the maintainers setup an official base image, with the required hooks to keep it up to date?

**Comment by joelanford** [comment]
@cpitman I definitely agree. We're planning to migrate this operator into the `operator-framework/operator-sdk` repository so that new helm operators can be created with the `operator-sdk` binary. Part of that migration will very likely include what you've described. 

Run this command with the latest `operator-sdk` binary to get a feel for how it currently works for the ansible operator:
```sh
operator-sdk new my-spring-boot --type=ansible --api-version=example.org/v1alpha1 --kind=SpringBoot
```

**Comment by cpitman** [comment]
Awesome, I am trying out the Ansible operator as well. I'll close this for now.
